#!/bin/bash

SRC_DIR="./pdfs"
DEST_DIR="./txts"
red='\033[0;31m'
green='\033[0;32m'
nc='\033[0m'
default_err="Unknown error occurred"

error() {
    msg="${1:-$default_err}"
    echo -e "${red}${msg}${nc}"
}

msg() {
    msg="${1:-nothing}"
    echo -e "${green}${msg}${nc}"
}

for f in "${SRC_DIR}/"*.pdf; do
  msg "Trying ${f}"
  fname=${f##*/}
  fname_noext=${fname%.*}
  output="${DEST_DIR}/${fname_noext}.txt"
  pdftotext -q "${f}" "${output}"
  fsize=$(stat -c%s "${output}")
  if [ $fsize -le 100 ]; then
    error "${f} looks like a non-native pdf."
    msg "Trying convert and tesseract OCR"
    img_temp="${fname_noext}.jpeg"
    convert -density 300 "${f}" -quality 10 -blur 1 -auto-level "${img_temp}"
    result=""
    for img in "${fname_noext}"-*.jpeg; do
      out=$(tesseract "${img}" stdout)
      result="${result}\n\n${out}"
      rm -f "${img}"
    done
    echo -e "${result}" > "${output}"
  fi
done
