#!/bin/bash

SRC_DIR="./pdfs"
DEST_DIR="./txts"
red='\033[0;31m'
green='\033[0;32m'
nc='\033[0m'
default_err="Unknown error occurred"

error() {
    msg="${1:-$default_err}"
    echo -e "${red}${msg}${nc}"
}

msg() {
    msg="${1:-nothing}"
    echo -e "${green}${msg}${nc}"
}

for f in "${SRC_DIR}/"*.pdf; do
  msg "Trying ${f}"
  fname=${f##*/}
  fname_noext=${fname%.*}
  output="${DEST_DIR}/${fname_noext}"
  pdftotext -q "${f}" "${output}"
  fsize=$(stat -c%s "${output}")
  if [ $fsize -le 100 ]; then
    msg "${f} looks like a non-native pdf. Trying convert and tesseract OCR"
    img_temp="${fname_noext}.png"
    convert -density 300 "${f}" -quality 60 -blur 5 -background white -alpha remove -colorspace gray -white-threshold 25% "${img_temp}"
    tesseract "${img_temp}" "${output}"
    rm -f "${img_temp}"
  fi
done
